version: '3'
services:
  view-container:
    build:
      context: .
      dockerfile: Dockerfile.view
    ports:
      - 80:80
    restart: always

  logic-container:
    build:
      context: .
      dockerfile: Dockerfile.logic
