FROM cirrusci/flutter:latest

WORKDIR /app

# Create a non-root user
RUN adduser --disabled-password --gecos '' nonroot
USER nonroot

# Copy the pubspec files and install dependencies
COPY pubspec.* ./

# Copy the remaining app files
COPY . .

# Build the Flutter app
RUN flutter build apk
