# Build stage
FROM cirrusci/flutter AS build
WORKDIR /app
COPY pubspec.* ./
COPY . .
RUN flutter build web

# Production stage
FROM nginx:alpine
COPY --from=build /app/build/web /usr/share/nginx/html
EXPOSE 80
